---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zude.
--- DateTime: 2023/9/22 13:42
---
a=1
a1=0
b=2
c=3

shallowCopy = function(x)
    local y = {}
    if x == nil then return y end
    for k, v in pairs(x) do y[k] = v end
    return y
end

update = function(b, x, inplace, false_as_nil)
    local y = inplace and b or shallowCopy(b)
    if x == nil then return y end
    for k, v in pairs(x) do
        if false_as_nil and v == false then v = nil end
        y[k] = v
    end
    return y
end

transfer_global_variable = function(prefix, save_prefix)
    local stem
    -- 存在了几个月的BUG：遍历key的过程中修改key
    local G = {}
    for k, v in pairs(_G) do
        if k:startsWith(prefix) then
            stem = string.sub(k, #prefix + 1)
            if save_prefix and #save_prefix > 0 then
                G[save_prefix .. stem] = _G[stem] or false
            end
            G[stem] = v
        end
    end
    update(_G, G, true)
end

transfer_global_variable("a","d")